### PR TITLE
bump to next minor release

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
This PR includes these changes;

- Update all dependencies (include devDeps).
- Modernize the code and improve the logic.
- Update README.md file

> Ready to publish the next minor release (2.1.0)

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
@titanism, I will merge this PR then you can bump it to 2.1.0, update the History file and publish it until I will have access to all modules on npm.

**Comment by titanism** [comment]
@dead-horse we need access to this too, `npm owner add titanism koa-json` please!

**Comment by 3imed-jaberi** [comment]
cool, don't forget to give me too the access

**Comment by titanism** [comment]
@3imed-jaberi yeah if we get access we will def add you 👍 🙇

**Comment by titanism** [comment]
@3imed-jaberi perhaps if we don't hear back after a week we could move this to scoped `@koajs` package, along with all the others, but that's plenty of work ...

**Comment by 3imed-jaberi** [comment]
It would be better to move it and move all "official" modules under the scope ... I think we need to create a private channel in slack to discuss things like this, decide to re-write some modules with typescript, keep koa ecosystem cleaner for new come by avoiding the many modules to solve the same problem, provide better documentation web site, try to build a community in slack and/or discord anything like that and collaborate as much as possible with maintainers/contributors of the other tools and frameworks which based on koa like ladjs ...etc

**Pull request merged**
